In [1]:
pip install xlrd

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt


# 1. Read the dataset to python environment

In [3]:
iris_data=pd.read_excel(r'C:\dsa\iris.xls')

In [4]:
iris_data.head()

SL   SW   PL   PW Classification
0  5.1  3.5  1.4  0.2    Iris-setosa
1  4.9  3.0  1.4  0.2    Iris-setosa
2  NaN  3.2  1.3  0.2    Iris-setosa
3  4.6  3.1  1.5  0.2    Iris-setosa
4  5.0  3.6  1.4  0.2    Iris-setosa

# 2.Do the necessary pre-processing steps


In [5]:
iris_data.info()

iris_data.isnull().sum

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   SL              143 non-null    float64
 1   SW              144 non-null    float64
 2   PL              144 non-null    float64
 3   PW              150 non-null    float64
 4   Classification  150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


<bound method NDFrame._add_numeric_operations.<locals>.sum of         SL     SW     PL     PW  Classification
0    False  False  False  False           False
1    False  False  False  False           False
2     True  False  False  False           False
3    False  False  False  False           False
4    False  False  False  False           False
..     ...    ...    ...    ...             ...
145  False  False  False  False           False
146  False  False  False  False           False
147  False  False   True  False           False
148  False  False  False  False           False
149  False  False  False  False           False

[150 rows x 5 columns]>

In [6]:
iris_data.shape

(150, 5)

In [7]:
##1)Imputing with constant value
##duplicate of the original dataframe
iris_constant=iris_data
##replace with a constant value
constant_value=0
iris_constant.fillna(constant_value,inplace=True)
iris_constant.info()
iris_constant.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column          Non-Null Count  Dtype  
---  ------          --------------  -----  
 0   SL              150 non-null    float64
 1   SW              150 non-null    float64
 2   PL              150 non-null    float64
 3   PW              150 non-null    float64
 4   Classification  150 non-null    object 
dtypes: float64(4), object(1)
memory usage: 6.0+ KB


SL   SW   PL   PW Classification
0  5.1  3.5  1.4  0.2    Iris-setosa
1  4.9  3.0  1.4  0.2    Iris-setosa
2  0.0  3.2  1.3  0.2    Iris-setosa
3  4.6  3.1  1.5  0.2    Iris-setosa
4  5.0  3.6  1.4  0.2    Iris-setosa

In [8]:
##Encoding
##Onehot encoding

In [9]:
data=pd.DataFrame(iris_constant)

In [10]:
from sklearn.preprocessing import OneHotEncoder
encoder=OneHotEncoder()
encoded_results=encoder.fit_transform(data).toarray()
encoded_results

array([[0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [1., 0., 0., ..., 1., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [29]:
##Label encoding
iris_constant['Classification']


0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: Classification, Length: 150, dtype: object

In [43]:
from sklearn.preprocessing import LabelEncoder
data=pd.DataFrame({"Classification":["Iris-setosa","Iris-versicolor","Iris-virginica"]})
column_to_encode="Classification"
column_to_encode_values=data[column_to_encode]
label_encoder=LabelEncoder()
encoded_labels=label_encoder.fit_transform(column_to_encode_values)
data["encoded_Classification"]=encoded_labels

In [44]:
data.head()

Classification  encoded_Classification
0      Iris-setosa                       0
1  Iris-versicolor                       1
2   Iris-virginica                       2

# 3. Find out which classification model gives the best result

In [30]:
iris_constant.head()

SL   SW   PL   PW Classification
0  5.1  3.5  1.4  0.2    Iris-setosa
1  4.9  3.0  1.4  0.2    Iris-setosa
2  0.0  3.2  1.3  0.2    Iris-setosa
3  4.6  3.1  1.5  0.2    Iris-setosa
4  5.0  3.6  1.4  0.2    Iris-setosa

In [31]:
X=iris_constant.iloc[:,:-1].values
y=iris_constant['Classification']

In [35]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [36]:
##Train the models

In [67]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier


In [76]:
##Create and train a support vector classifier
svc_classifier=SVC()
svc_classifier.fit(X_train,y_train)
##Create and train a K-nearest neighbors classifier
knn_classifier=KNeighborsClassifier()
knn_classifier.fit(X_train,y_train)
##Create and train DecisionTree classifier
dt_classifier=DecisionTreeClassifier()
dt_classifier.fit(X_train,y_train)
##Create and train RandomForestClassifier 
rf_classifier=RandomForestClassifier()
rf_classifier.fit(X_train,y_train)


RandomForestClassifier()

In [77]:
##make predictions on test data
svc_predictions=svc_classifier.predict(X_test)
knn_predictions=knn_classifier.predict(X_test)
dt_predictions=dt_classifier.predict(X_test)
rf_predictions=rf_classifier.predict(X_test)


In [78]:
##Evaluate
from sklearn.metrics import accuracy_score
svc_accuracy=accuracy_score(y_test,svc_predictions)
knn_accuracy=accuracy_score(y_test,knn_predictions)
dt_accuracy=accuracy_score(y_test,dt_predictions)
rf_accuracy=accuracy_score(y_test,rf_predictions)


In [79]:
print("Support Vector Classifier Accuracy:",svc_accuracy)
print("K-Neighbor Classifier Accuracy:",knn_accuracy)
print("DecisionTree Classifier Accuracy:",dt_accuracy)
print("RandomForest Classifier Accuracy:",rf_accuracy)


Support Vector Classifier Accuracy: 0.9333333333333333
K-Neighbor Classifier Accuracy: 0.9
DecisionTree Classifier Accuracy: 1.0
RandomForest Classifier Accuracy: 1.0


In [41]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [42]:
##confusion matrix and classification report give more details about performance
print(confusion_matrix(svc_predictions,y_test))

print(classification_report(knn_predictions,y_test))

[[10  1  0]
 [ 0  8  1]
 [ 0  0 10]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      0.83      0.91        12
Iris-versicolor       0.78      1.00      0.88         7
 Iris-virginica       0.91      0.91      0.91        11

       accuracy                           0.90        30
      macro avg       0.90      0.91      0.90        30
   weighted avg       0.91      0.90      0.90        30



In [ ]:
##DecisionTree classifier and Random Forest classifier are the best methods here.Because both these have high accuracy compared with other two.